# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: obsolete29
email: obs29001@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A sysadmin trying find his way. Foosball, biking, hiking, reading. My cats are goblins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://obsolete29.com" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Chicago
show_excerpts: true # Show excerpts of posts on the home page
permalink: /:categories/:title/ # Don't show the date of the post in the URL

# Social
twitter_username: obsolete29
github_username: obsolete29

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

include: [_pages]



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
